### ISSUE TITLE
Requesting  attachment of documents

### ISSUE THREAD

**Issue by Venkytharun13** [Tharunvenky06/WhatsUp_Development#4]
Dear Tharunvenky06,

It would be great if you could include the documents in the attachments section 
Kindly add this feature

**Comment by Tharunvenky06** [comment]
Dear Venkytharun13,

Thanks for suggesting this feature . We will add and let you know

**Comment by Tharunvenky06** [comment]
Dear Venkytharun13 ., Thanks for your valuable suggestion  . This feature enhancement makes our product great
